### ISSUE TITLE
Probable requête incompatible pour le module espace membre

### ISSUE THREAD

**Issue by Ikodi-julien** [Quillers/forum#1]
Après s'être loggué, si on veut modifier son pseudo par exemple, sa mouline.
Probablement une requête qui contient des " ?

**Comment by Ikodi-julien** [comment]
Remettre le serveur à jour après modif ? 
:-))

**Comment by vde-guil** [comment]
Penses à vérifier que tu appelles bien le nom du schema devant le nom de table, dans tes requetes. Ca peut venir de la!

**Comment by Flo-Nz** [comment]
Alors étrangement, ça tourne chez moi en local. 
@Ikodi-julien tu me disais qu'on avait pas besoin de mettre forum. devant les noms de table, tu penses que ça vient de là ?

**Comment by Ikodi-julien** [comment]
oui, sur le serveur il a fallut différencier le nom d'utilisateur du nom de la base, donc il faut repréciser "forum" ...
D'ailleurs, il faudra idéalement changer le nom de base et d'utilisateur en local pour que ça soit compatible directement sur le serveur... désolé :-/
