### ISSUE TITLE
Création de nouveau topic dans une catégorie renvoi une erreur

### ISSUE THREAD

**Issue by Ikodi-julien** [Quillers/forum#2]
createNewTopic error: error: syntax error at or near "'title'" at Parser.parseErrorMessage (/home/quiltuuc/nodevenv/forum_subDir/10/lib/node_modules/pg-protocol/dist/parser.js:278:15) at Parser.handlePacket (/home/quiltuuc/nodevenv/forum_subDir/10/lib/node_modules/pg-protocol/dist/parser.js:126:29) at Parser.parse (/home/quiltuuc/nodevenv/forum_subDir/10/lib/node_modules/pg-protocol/dist/parser.js:39:38) at Socket.stream.on (/home/quiltuuc/nodevenv/forum_subDir/10/lib/node_modules/pg-protocol/dist/index.js:10:42) at Socket.emit (events.js:198:13) at addChunk (_stream_readable.js:288:12) at readableAddChunk (_stream_readable.js:269:11) at Socket.Readable.push (_stream_readable.js:224:10) at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Hélas la requête semble correcte donc pas évident au premier abord :**
 createNewTopic: (newTopic, callback) => {
    const query = `INSERT INTO forum.topic ('title', 'topic_description', 'author', 'category_id') VALUES
        ($1, $2, $3, $4)`;
    client.query(query, [newTopic.title, newTopic.topicDesc, newTopic.author, newTopic.categoryId], callback);
  },

**Comment by vde-guil** [comment]
yes j'ai vu ca, c'est les simples quotes, le probleme (soit double, soit pas de quotes pour les noms de champs). J'ai eu le meme probleme en local en pullant from main.
J'ai regle ca, c'est bon!
