### ISSUE TITLE
Les "bannières" de noms de catégories ne sont pas toutes alignées pareil dans la page catégories...

### ISSUE THREAD

**Issue by Ikodi-julien** [Quillers/forum#3]
C'est peut-être un détail pour vous...
![image](https://user-images.githubusercontent.com/63581205/107991252-816cae80-6fd6-11eb-8b4c-a6236ffcc79d.png)

**Comment by Camillodo** [comment]
Bug du a une regle générale:
img{
max-width:400px;}
du coup toutes les images de tout le site se bloquait a cette position. De maniere générale ne pas stylisé la balise image toute seule, soit la cibler avec une class, soit par rapport a son conteneur.
Des bisous du love et des positions absolutes
